export const GET_TOTAL_OFFERS_BY_NAME = "GET_TOTAL_OFFERS_BY_NAME";

export const GET_TOTAL_INTERNSHIPS_BY_DAY = "GET_TOTALINTERNSHIPS_BY_DAY";
export const GET_TOTAL_JOBS_BY_DAY = "GET_TOTAL_JOBS_BY_DAY";

export const GET_TOTAL_INTERNSHIPS_COUNT = "GET_TOTAL_INTERNSHIPS_COUNT";
export const GET_TOTAL_JOBS_COUNT = "GET_TOTAL_JOBS_COUNT";

export const GET_TOTAL_INTERNSHIPS_GENDER_BY_DAY =
  " GET_TOTAL_INTERNSHIPS_GENDER_BY_DAY";
export const GET_TOTAL_JOBS_GENDER_BY_DAY = "GET_TOTAL_JOBS_GENDER_BY_DAY";
