export const GET_APPOINTMENT = "GET_APPOINTMENT";
export const ADD_APPOINTMENT = "ADD_APPOINTMENT";
export const MODIFY_APPOINTMENT = "MODIFY_APPOINTMENT";
export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT";
