export const GET_CANDITATURE = "GET_CANDITATURE";
export const ADD_CANDITATURE = "ADD_CANDITATURE";
export const MODIFY_CANDIDATURE = "MODIFY_CANDIDATURE";
export const ADD_INTERVIEW_DATE = "ADD_INTERVIEW_DATE";
